### PR TITLE
Fix typo & Improvements 

### PR DESCRIPTION
**Pull request by AbderrahimSoubaiElidrissi**

### CODE REVIEW

**Comment by AbderrahimSoubaiElidrissi** [comment]
@yjose

**Comment by zHaytam** [comment]
"Technology" is actually also valid (StackOverflow uses it too).
It's because we're only talking about one field (dev).

**Comment by yjose** [comment]
agree with @zHaytam

**Comment by AbderrahimSoubaiElidrissi** [comment]
@zHaytam @yjose  Make sense ;)

**Pull request closed without merging**
