### PR TITLE
[WIP] 2021 results first preview

### PR DESCRIPTION
**Pull request by yjose**
@ezzarghili @aboullaite @AbderrahimSoubaiElidrissi @iMeriem @Iduoad @otmos @ridaouiafaf if you have some time, we need your help on writing comments about this year's results here is an example from last year.
Pick one of the categories and update files to open a new PR
https://github.com/DevC-Casa/stateofdev.ma/tree/2021-results/results/2021/sections

* Overview  @djalal ✅
* Profile ✅. @Iduoad
* Education  @yjose ✅
* Work @yjose ✅
* Tech @yezz123 ✅
* Community @yjose ✅

### CODE REVIEW

**Comment by yjose** [comment]
@ezzarghili  @aboullaite @AbderrahimSoubaiElidrissi @iMeriem   if you have some time, we need your help on writing comments about this year's results here is an example from last year. 
 Pick one of the categories and update files to open a new PR 
https://github.com/DevC-Casa/stateofdev.ma/tree/2021-results/results/2021/sections

* Profile 
* Education
* Work 
* Tech 
* Community 



I will take care of Work and community

**Comment by djalal** [comment]
wording: replace "salaries" title with more detailed, e.g "Level of salary"

Screen Shot 2021-12-17 at 10 15 53

**Comment by djalal** [comment]
bug: in 2021 results, when a question is selected in the list on the left, it often shows the wrong answer on the right block. here are two examples:

Screen Shot 2021-12-17 at 11 16 31
Screen Shot 2021-12-17 at 11 17 23

**Comment by djalal** [comment]
usability: link to download raw results still goes to 2020

Screen Shot 2021-12-17 at 11 04 21

**Comment by djalal** [comment]
discrepancy: there are two entries for Angular

Screen Shot 2021-12-17 at 10 30 56

**Comment by djalal** [comment]
usability: default result set is "2020", it should be "2021", i.e the most recent by default

Screen Shot 2021-12-17 at 11 05 18

**Comment by djalal** [comment]
visualization: these data points would be more readable on a line graph, like the attached sample Screen Shot 2021-12-17 at 10 16 47
Salary-by-Experience14

**Comment by djalal** [comment]
formatting: seeing some HTML tags in the main text block:
 - "In November 2021, \<strong\> 1098 developers from Morocco 🇲🇦 \</strong\>"

**Comment by otmos** [comment]
I'm getting some weird bugs , i'm getting graphs corresponding to different
questions than the ones selected :
https://deploy-preview-71--stateofdev.netlify.app/playground/#condition=%5B%5D&groupBy&question=profile-q-7
[image: image.png]
ᐧ

**Comment by yjose** [comment]
@djalal @otmos 
* `usability: default result set is "2020", it should be "2021", i.e the most recent by default `✅
* `discrepancy: there are two entries for Angular`: Not a bug its two different frameworks 
*  `formatting: seeing some HTML tags in the main text block`: ✅
* `usability: link to download raw results still goes to 2020` : we need to complete the report to generate the `.zip` file 😀
* `wording: replace "salaries" title with more detailed, e.g "Level of salary"`:  work on progress for Categories comments 
* `visualization: these data points would be more readable on a line graph, like the attached sample`: I think we should think to implement  it, but right now we only support charts maybe in the upcoming versions

**Comment by yezz123** [comment]
Screen Shot 2021-12-18 at 15 39 35

I have a question about SQL5 is people truly give importance to SQL Version cause I guess most of the people that vote for it just read SQL and choose it, That's why I guess it's better to not add the version of SQL, that's why I guess its better to let it only SQL.

Also is HTML/CSS special to add emoji 😂

**Comment by yezz123** [comment]
Screen Shot 2021-12-18 at 15 39 57

If someone could help I didn't get it, PHP is a language or we can define it also as a platform 🤔 ?
cc @makraz

**Comment by yezz123** [comment]
Screen Shot 2021-12-18 at 15 48 36

I guess here we could add a similar title to `Front-end frameworks/libraries` where we write `Languages`.

**Comment by djalal** [comment]
@yjose overview processed in #73, PTAL 👍

**Comment by yjose** [comment]
@yezz123  can't answer all questions right now, can you please add  comments to  [Tech category](https://github.com/DevC-Casa/stateofdev.ma/tree/2021-results/results/2021/sections)   you can get some inspiration from [last year report ](https://stateofdev.ma/2020/)

**Comment by yjose** [comment]
@djalal check my comment on PR

**Comment by yjose** [comment]
@all-contributors please add @yezz123 for content

**Comment by yjose** [comment]
@all-contributors please add @Iduoad  for content

**Pull request merged**
