### PR TITLE
Docs: Add Tech Notes

### PR DESCRIPTION
**Pull request by yezz123**
@yjose @djalal a simple review please

### CODE REVIEW

**Comment by yjose** [comment]
looks good so far, still in progress right as you didn't add notes for questions 11-15?

**Comment by yezz123** [comment]
> looks good so far, still in progress right as you didn't add notes for questions 11-15?

Working on Them right now

**Comment by yezz123** [comment]
cc @yjose

**Comment by yjose** [comment]
thanks @yezz123  , looks good 🙏

**Pull request merged**
