### PR TITLE
first analsyis notebook

### PR DESCRIPTION
**Pull request by Elamraoui-Sohayb**
Convering raw JSON results to CSV, and decoding answer values into original choices.

### CODE REVIEW

**Comment by yjose** [comment]
hey, @Elamraoui-Sohayb  thanks for your contribution 🙌, i am not sure if I have the knowledge to review your PR.  but I suggest remove space in filename `Simple Preprocessing.ipynb`  😄 .  

@AbderrahimSoubaiElidrissi  can you help with this, please

**Comment by AbderrahimSoubaiElidrissi** [comment]
Thank you for your contribution @Elamraoui-Sohayb 
@yjose Sure I will take a look

**Comment by Elamraoui-Sohayb** [comment]
Thanks for your reply. I have removed the spaces in the filename.
The result files (csv) can be added to raw Zip after your review.

**Comment by AbderrahimSoubaiElidrissi** [comment]
Hello @Elamraoui-Sohayb 
I liked the idea to convert the raw data to CSV (as the universal data for AI/ML) that will inspire more data scientists to contribute with models.

- [ ] I think it will be useful to add a value (sum of values) for every question  in **results_preprocessed.csv**
- [X] for **question_preprocessed.csv** I think we are good as the file can be used as a labels dataset.
- [ ] If we can replace **NaN** values with 0 will be more accurate.
- [ ] Ideally, fix `SettingWithCopyWarning` (if not it's okay)
- [ ] Add a section in Readme.md file to highlight your work 
- [ ] Add yourself as a contributor
- [ ] provide a zip file and if we can  add this to Kaggle will be a good thing (@yjose we can think to create a profile in Kaggle for DevC and add dataset + notebook )

**Review by AbderrahimSoubaiElidrissi — COMMENTED** [review]
Check my comment on PR :arrow_up:

**Comment by Elamraoui-Sohayb** [comment]
Thank you @AbderrahimSoubaiElidrissi for the review.

1.  I have added the data to Kaggle to do some data analysis ([Link here](https://www.kaggle.com/amr009/state-of-dev-mrocco-2020)). The idea of a DevC Kaggle account is very good (creating it as an organization so others can join would be better), i can transfer ownership of the dateset easily once the DevC account created.

1. Replacing NaN with 0: The data has some columns (Event_Attended, Talks_Participation) that accept 0 as a **choice** (categorical variable), so replacing NaN with 0 will be confusing, plus there is plenty of methods in Numpy and Pandas to handle existing NaNs in the analysis phase.

1. Adding (Sum of Values): can you please clarify what to calculate exactly? I can think of **"How many people answered/skipped a question?"** or **"How many possible choices, i.e values, each question accepts?"**

1.  SettingWithCopyWarning , adding Readme  file, adding myself as contributor: Done :white_check_mark:

**Comment by AbderrahimSoubaiElidrissi** [comment]
@Elamraoui-Sohayb Cool
For the 4th point, I was thinking to provide some relevant data for the consumer of CSV (ie. how many people answered a question) but I think this is another thing and it has nothing with your pull request so we can open a new issue for it.

**Comment by AbderrahimSoubaiElidrissi** [comment]
@yjose LGTM 
@yjose @aboullaite   Let's see what we can do for DevC organization in Kaggle

**Comment by yjose** [comment]
@Elamraoui-Sohayb I just create a new account https://www.kaggle.com/devccasa 
should work?

**Comment by aboullaite** [comment]
> @Elamraoui-Sohayb I just create a new account https://www.kaggle.com/devccasa
> should work?

Can we move the challenge that Sohayb created over there ?

**Pull request merged**
