### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by zHaytam**
I'm creating this PR as a WIP so that I know what you guys think and what am I allowed to edit/change etc.
Feel free to stop me or reject anything you don't see fit!

I started with the Overview and will be going in order.

### CODE REVIEW

**Comment by yjose** [comment]
sorry @zHaytam, I didn't notice your PR and I merged djalal PR before yours 🙏 , can you please resolve conflicts

**Comment by zHaytam** [comment]
No problem, give me 5 minutes.

**Comment by zHaytam** [comment]
Done.

**Comment by yjose** [comment]
👍

**Pull request merged**
